name:                minilang
version:             0.1.0.0
github:              https://github.com/abailly/minilang
license:             BSD3
author:              "Arnaud Bailly"
maintainer:          "arnaud@aleryo.com"
copyright:           "2018 Arnaud Bailly"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/minilang#readme>

default-extensions:
- DeriveGeneric
- OverloadedStrings
- FlexibleInstances
- MultiParamTypeClasses
- FlexibleContexts
- RecordWildCards
- NamedFieldPuns

ghc-options: -Wall -fno-warn-orphans -Werror

dependencies:
  - aeson
  - async
  - base
  - bytestring
  - containers
  - concurrency
  - data-default
  - directory
  - exceptions
  - filepath
  - haskeline
  - mtl
  - parsec
  - prettyprinter
  - stm
  - text
  - unix
  - unordered-containers
  - wai
  - wai-app-static
  - wai-extra
  - wai-websockets
  - warp
  - websockets

library:
  source-dirs: src


executables:
  mli:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - minilang
    - optparse-applicative
    - text
    - unix

tests:
  minilang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - async
    - base
    - directory
    - filepath
    - minilang
    - haskeline
    - hspec
    - hspec-discover
    - http-conduit
    - http-types
    - parsec
    - QuickCheck
    - text
    - unix
    - wai
    - warp
    - websockets
