name:                minilang
version:             0.1.0.0
github:              https://github.com/abailly/minilang
license:             BSD3
author:              "Arnaud Bailly"
maintainer:          "arnaud@aleryo.com"
copyright:           "2018 Arnaud Bailly"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/minilang#readme>

dependencies:
- base >= 4.7 && < 5

default-extensions:
- DeriveGeneric
- OverloadedStrings
- FlexibleInstances
- MultiParamTypeClasses
- FlexibleContexts

ghc-options: -Wall -Werror

library:
  source-dirs: src
  exposed-modules:
  - Minilang.Parser
  - Minilang.Eval
  - Minilang.Normalize
  - Minilang.REPL
  dependencies:
  - base
  - containers
  - directory
  - mtl
  - parsec
  - text
  - unix


executables:
  mli:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - minilang
    - text

tests:
  minilang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - directory
    - minilang
    - hspec
    - hspec-discover
    - text
    - unix
