name: atbordeaux2020
synopsis: HAskell code for AT Bordeaux 2020
maintainer: Arnaud Bailly <arnaud.oqube@gmail.com>
github: abailly/xxi-century-typed
category: Development

ghc-options: -Wall -Werror
default-extensions:
  - DuplicateRecordFields
  - RecordWildCards
  - GADTs
  - FlexibleContexts
  - FlexibleInstances
  - OverloadedStrings

dependencies:
  - array
  - base >= 4.9 && < 5
  - basement
  - bytestring
  - mtl
  - parsec
  - text

library:
  source-dirs: .
  exposed-modules:
    Presentation
  dependencies:
  - hspec
  - QuickCheck
